### ISSUE TITLE
[Feature] Highlight summary

### ISSUE THREAD

**Issue by jmaliksi** [BeeFox-sys/blasebot#4]
I'm filing this for me, really, to try to implement but also because I will forget.

It would be neat to be able to type `bb!highlights 8` and get the last 8 days of outcomes, ie so you can catch up after sleeping

**Comment by jmaliksi** [comment]
> you might want to move the handleEvents() from gameUpdates into the gameUtils so it can be referenced from there
> then you could probably just grab the last 8 days with getGames() and cycle through that with the handle events and send the output

**Comment by BeeFox-sys** [comment]
Sadly I do not feel this is quite in the scope of blasebot, as it is more for the now. Reblase is amazing for this sort of thing though! and we now have the feed on the site, so I will be closing this req c:
