### ISSUE TITLE
The "allergic to peanuts" spoiler reveals itself through width

### ISSUE THREAD

**Issue by porglezomp** [BeeFox-sys/blasebot#5]
Here's a "yes"
<img width="141" alt="Screen Shot 2020-09-17 at 23 44 32" src="https://user-images.githubusercontent.com/1690225/93552904-c4e7c180-f93f-11ea-8a68-0811838f210b.png">
And here's a "no"
<img width="141" alt="Screen Shot 2020-09-17 at 23 44 24" src="https://user-images.githubusercontent.com/1690225/93552916-c913df00-f93f-11ea-848c-6d9197b2054a.png">

Since they're different widths, they reveal the answer without clicking.
Probably the safest option for fully obscuring it would be to use:
```
||`Yes`||
||`No `||
```

**Comment by BeeFox-sys** [comment]
I will look into it c:

**Comment by BeeFox-sys** [comment]
fixed, will be live next restart
