### ISSUE TITLE
Cannot add hosted bot to server due to Discord's new Privileged Intents rules

### ISSUE THREAD

**Issue by 10thTARDIS** [BeeFox-sys/blasebot#6]
When trying to add the bot to my server, Discord says it cannot be added because it hasn't gone through their review process.

https://support.discord.com/hc/en-us/articles/360040720412-Bot-Verification-and-Data-Whitelisting

**Comment by BeeFox-sys** [comment]
yup! we know! this is discords end issue, we've been waiting for verification for about a month now ("""5 day turnaround""")

**Comment by 10thTARDIS** [comment]
Sounds like you have it handled, then!  Sorry to bring it up, just wanted to make sure you were aware since I didn't see any comments regarding it.  :)

**Comment by BeeFox-sys** [comment]
Going to leave this open until the bot is verified so people can see this issue

**Comment by BeeFox-sys** [comment]
Oh whoops it's verified now
